# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm9zyOhM237M-_snXROls5J4c8Ztdjdx
"""

idade = int(input("digite sua idade: "))

if idade >= 18:
  print("voce eh maior de idade")
else:
  print("voce nao eh maior de idade")